version: '3'
services:
    front:
      image: docker-tutorial/front
      build:
        context: client
        dockerfile: front.dockerfile
      command: npm run serve
      ports:
        - "8080:8080"
    web:
      image: docker-tutorial/web
      command: python manage.py runserver
      build:
        context: ./
        dockerfile: web.dockerfile
      ports:
        - "5000:5000"
      volumes:
        - .:/backend/hms
      depends_on:
        - db
        
    db:
      image: mongo:4.4

    